### ISSUE TITLE
Update susceptibility to 55.3%

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#119]
Based on new data as of October 2, 2021

**Comment by shagunn** [comment]
@JoviaNierenberg since we are calculating susceptibility proportion based on location and infection data from covidestim in app.py I dont think this is issue is needed anymore? Just wanted to check with you before I closed the issue. 
The susceptibility proportion for USA based on the last covidestim data update (nov 26) is 0.544 so that seems about right.
