### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by JoviaNierenberg** [JoviaNierenberg/COVID-Event-Safety-Modeling#27]
A lot of assumptions in this paragraph especially need citations because they inherently assume homogeneity and/or uniformity (which are incongruous with real world populations but may be the best we can do for the time-being)

**Comment by JoviaNierenberg** [comment]
Read through testing paragraph, update/comment as needed.

**Comment by s67sea** [comment]
The testing paragraph had 3 main areas where assumptions were made: testing, infection and contracting the disease between testing time and the event. 

For testing, assuming uniformity makes sense

For infection, we should probably be assuming that infected people are in the first 5 days of the disease (prior to exhibiting symptoms) since I think we already have a line saying we assume symptomatic people won't show up

I'm not sure what the last 3 lines mean. Doesn't "remaining time before event" and "time since PCR tests are perform" refer to the same 1-3 days prior to the event?

**Comment by s67sea** [comment]
left comments on the paragraph
